# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
app_identifier "com.BangBangStudios.Would-You-Rather" # The bundle identifier of your app
username("thankmelater23@me.com") # Your Apple Developer Portal username

